from pathlib import Path
import json,sys
root=Path(sys.argv[1] if len(sys.argv)>1 else '.').resolve()
policy=root/'fix3-policy.js'; bg=root/'background.js'; manifest=root/'manifest.json'
s=policy.read_text(encoding='utf-8-sig')
old="""  function routeBonus(desc,intent){if(!flags.adaptiveRouting)return 0;let n=baseName(desc),q=String(intent??``).toLowerCase(),b=0;let file=/(?:\\u6587\\u4ef6|\\u76ee\\u5f55|\\u8bfb\\u53d6|\\u67e5\\u770b|\\u641c\\u7d22|\\u67e5\\u627e|file|folder|directory|read|search|find|grep)/i.test(q),edit=/(?:\\u4fee\\u6539|\\u7f16\\u8f91|\\u5199\\u5165|\\u66ff\\u6362|\\u8865\\u4e01|edit|modify|write|patch|replace)/i.test(q),cmd=/(?:\\u547d\\u4ee4|\\u6267\\u884c|\\u8fd0\\u884c|\\u7ec8\\u7aef|\\u6784\\u5efa|\\u6d4b\\u8bd5|powershell|command|shell|run|exec|build|test)/i.test(q),git=/(?:git|github|\\u4ed3\\u5e93|\\u63d0\\u4ea4|\\u5206\\u652f|commit|branch|repo)/i.test(q);if(file&&/(read|list|find|search|grep|stat|snapshot)/.test(n))b+=650;if(edit&&/(patch|write|edit|replace)/.test(n))b+=800;if(edit&&/(read|find|search|grep)/.test(n))b+=260;if(cmd&&/(run_command|shell|exec|run)/.test(n))b+=900;if(edit&&cmd&&/(run_command|shell|exec|run)/.test(n))b+=400;if(git&&/(git|run_command|shell|exec)/.test(n))b+=620;return b}
"""
new="""  function routeBonus(desc,intent){if(!flags.adaptiveRouting)return 0;let n=baseName(desc),q=String(intent??``).toLowerCase(),b=0;let file=/(?:\\u6587\\u4ef6|\\u76ee\\u5f55|\\u8bfb\\u53d6|\\u67e5\\u770b|\\u641c\\u7d22|\\u67e5\\u627e|file|folder|directory|read|search|find|grep)/i.test(q),note=/(?:obsidian|\\u9ed1\\u66dc\\u77f3|\\u7b14\\u8bb0|vault)/i.test(q),edit=/(?:\\u4fee\\u6539|\\u7f16\\u8f91|\\u5199\\u5165|\\u66ff\\u6362|\\u8865\\u4e01|edit|modify|write|patch|replace)/i.test(q),cmd=/(?:\\u547d\\u4ee4|\\u6267\\u884c|\\u8fd0\\u884c|\\u7ec8\\u7aef|\\u6784\\u5efa|\\u6d4b\\u8bd5|powershell|command|shell|run|exec|build|test)/i.test(q),git=/(?:git|github|\\u4ed3\\u5e93|\\u63d0\\u4ea4|\\u5206\\u652f|commit|branch|repo)/i.test(q);if(file&&/(read|list|find|search|grep|stat|snapshot)/.test(n))b+=650;if(file&&note&&/(run_command|shell|exec|run)/.test(n))b+=850;if(edit&&/(patch|write|edit|replace)/.test(n))b+=800;if(edit&&/(read|find|search|grep)/.test(n))b+=260;if(cmd&&/(run_command|shell|exec|run)/.test(n))b+=900;if(edit&&cmd&&/(run_command|shell|exec|run)/.test(n))b+=400;if(git&&/(git|run_command|shell|exec)/.test(n))b+=620;return b}
  function promptDescriptorCost(desc){if(!desc||typeof desc!==`object`)return 0;let text=[desc.invocationName,desc.title,desc.description].map(x=>String(x??``)).join(`\\r\\n`),schema;try{schema=JSON.stringify(desc.inputSchema??{})}catch{schema=``}let enc=typeof TextEncoder===`function`?new TextEncoder:null,bytes=x=>enc?enc.encode(x).byteLength:x.length;return bytes(text)+bytes(schema)*2+1024}
  function promptExposureSettings(descriptors,settings,intent){if(!flags.adaptiveRouting||!Array.isArray(descriptors)||!settings||typeof settings!==`object`)return settings;let enabled=descriptors.filter(d=>d?.execution?.enabled!==false),total=enabled.reduce((sum,d)=>sum+promptDescriptorCost(d),0),adaptiveBudget=Number.isInteger(settings.adaptiveMaxPromptBytes)&&settings.adaptiveMaxPromptBytes>0?settings.adaptiveMaxPromptBytes:14000,triggerBudget=Math.max(28000,adaptiveBudget*2);if(total<=triggerBudget)return settings;let servers=settings.servers&&typeof settings.servers===`object`&&!Array.isArray(settings.servers)?settings.servers:{},nextServers={...servers},changed=!1;for(let d of enabled){if(d?.provider?.kind!==`mcp`||!d.provider.id)continue;let id=d.provider.id,current=servers[id],mode=current?.mode??`direct`;if(mode!==`direct`)continue;nextServers[id]={mode:`adaptive`,pinnedDescriptorIds:Array.isArray(current?.pinnedDescriptorIds)?[...current.pinnedDescriptorIds]:[]},changed=!0}return changed?{...settings,servers:nextServers}:settings}
"""
if old not in s: raise SystemExit('Fix33105 route anchor missing')
s=s.replace(old,new,1)
old_export="g.DPP_FIX3=Object.freeze({flags,compactResult,modelBudget,classifyError,shouldRetry,retryDelay,noteRetry,routeBonus,recordSuccess,recentBonus,stepLimit,newLoopState,beforeCall,blockedResult,longCommandInfo,healthFromCache,status});"
new_export="g.DPP_FIX3=Object.freeze({flags,compactResult,modelBudget,classifyError,shouldRetry,retryDelay,noteRetry,routeBonus,promptDescriptorCost,promptExposureSettings,recordSuccess,recentBonus,stepLimit,newLoopState,beforeCall,blockedResult,longCommandInfo,healthFromCache,status});"
if old_export not in s: raise SystemExit('Fix33105 export anchor missing')
s=s.replace(old_export,new_export,1); policy.write_text(s,encoding='utf-8',newline='')
b=bg.read_text(encoding='utf-8-sig')
old_sz="async function sz(e,t){let[n,r]=await Promise.all([oR(e),Zu()]);return _d({descriptors:n,settings:r,intent:t}).descriptors}"
new_sz="async function sz(e,t){let[n,r]=await Promise.all([oR(e),Zu()]),i=globalThis.DPP_FIX3?.promptExposureSettings?.(n,r,t)??r;return _d({descriptors:n,settings:i,intent:t}).descriptors}"
if old_sz not in b: raise SystemExit('Fix33105 sz anchor missing')
b= b.replace(old_sz,new_sz,1); bg.write_text(b,encoding='utf-8',newline='')
m=json.loads(manifest.read_text(encoding='utf-8-sig')); m['version']='1.14.0.10';m['version_name']='1.14.0 ShunCode MCP Fix 3.3.10.5';manifest.write_text(json.dumps(m,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
for rel in ['_locales/en/messages.json','_locales/zh_CN/messages.json']:
 q=root/rel; txt=q.read_text(encoding='utf-8-sig').replace('Fix 3.3.10.4','Fix 3.3.10.5');q.write_text(txt,encoding='utf-8')
print('APPLY_FIX33105_PASS')
